"""added score column

Revision ID: e69fff51a624
Revises: 737b7f918473
Create Date: 2023-09-11 17:36:54.945755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69fff51a624'
down_revision = '737b7f918473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'score')
    # ### end Alembic commands ###
